### ISSUE TITLE
Prototype for list structs

### ISSUE THREAD

**Issue by tuchk4** [gcanti/tcomb#113]
```js
var listStruct = tcomb.list(tcomb.struct({
  id: tcomb.Num,
  name: tcomb.Str
}));

listStruct.prototype.doSomething = () => {

};

var list = new listStruct([{
  id: 1,
  name: 'test'
}, {
  id: 2,
  name: 'test2'
}]);

// list.doSomething == undefined
```

**Comment by gcanti** [comment]
Hi,
the `new` keyword in 

```js
var list = new listStruct([{
  id: 1,
  name: 'test'
}, {
  id: 2,
  name: 'test2'
}]);
```

is not necessary: `listStruct` is not a class constructor. As you noticed you can't define prototype methods. This is true for all the combinators except `struct`.
The job of `t.list(T)` is:

- a) check the elements type
- b) optionally create new instances of `T` if `T` is a struct
- c) in production it will be similar to the identity function, except for b)

This is by design (so you can work with native arrays).
