### ISSUE TITLE
modifying a type

### ISSUE THREAD

**Issue by benmonro** [gcanti/tcomb#149]
this is more of a question than an issue...

what is the ***proper*** way to modify a type on the fly?  

Suppose I want to add a field after a type has been defined.  From looking at the source I discovered that I can just do the following:

```
let MyType = t.struct({ ... });
///later on...
MyType.meta.props.MyNewField = t.enums.of("a b c");
```

but just curious if that's the correct way or if there's a better way...

**Comment by gcanti** [comment]
**Modifying** the type of a prop is the only solution I found in order to implement recursive types https://github.com/gcanti/tcomb/issues/71

**Adding** a prop is not completely supported at the moment due to this line https://github.com/gcanti/tcomb/blob/master/index.js#L327, but if you name your types shouldn't be a problem.

Honestly I don't know if there's a proper way, I never encountered a use case for this so I don't have a strong opinion.

**Comment by benmonro** [comment]
I found a bit of a hack that seems to work for my case.  In my case I just want to modify the type of a field (from enum to string) depending on the value of another field.  My hack is to just wrap type.meta.props in t.struct() call like this:

```
          var type = this.state.type;

            type.meta.props.State = t.maybe(value.Country === 'US' ? t.enums(this.props.data.states) : t.Str);

            this.setState({type: t.struct(type.meta.props), value})
```

**Comment by delaneyj** [comment]
@benmonro @gcanti I think I found a way to make this work in #146 with working example.

**Comment by benmonro** [comment]
Thanks @delaneyj 

I ended up going a different direction, although my solution did work, I felt it was a bit of a hack.  I decided to keep the schema static and instead made the UI options dynamic.  

Your solution looks very interesting though!  I'll keep it in mind if I end up needing something like that!

**Comment by ivan-kleshnin** [comment]
> Honestly I don't know if there's a proper way, I never encountered a use case for this so I don't have a strong opinion.

I see a lot of duplication in my types because there is constant need to define two similar types: one with **id** and one without **id**. Both types are required in different circumstances. For example, when you create a model in frontend it's common to not have `id` there until backend sync. But for same model in the backend you want to reuse the same type with `id` field checked.

I solve it in this way:
```js
let Name = Tc.subtype(Tc.String, x => {
  return x.length >= 1;
}); // notice no Type word here!

let AnketType = {
  id: Uid,
  name: Name,
  manufacturer: Manufacturer,
  assemblyDate: Tc.Date,
}; // notice "Type" word here

export default {
  Anket: Tc.struct(AnketType, "Robot"),
  AlmostAnket: Tc.struct(dissoc("id", AnketType), "AlmostRobot"),
};
```

Kinda clunky. I'd prefer to have something like this:

```js
let Name = Tc.subtype(Tc.String, x => {
  return x.length >= 1;
}); // no Type word here!

let Anket = {
  id: Uid,
  name: Name,
  manufacturer: Manufacturer,
  assemblyDate: Tc.Date,
}; // no "Type" word here

export default {
  Anket, AlmostAnket: Anket.dropField("id")
};
```

**Comment by gcanti** [comment]
> what is the proper way to modify a type **on the fly**?

Hi @ivan-kleshnin
I never encountered a use case that needed **a runtime change**.
At design time I use the `extend` function:

```js
const Name = Tc.subtype(Tc.String, x => {
  return x.length >= 1;
});

const AlmostRobot = Tc.struct({
  name: Name,
  manufacturer: Manufacturer,
  assemblyDate: Tc.Date
});

const Robot = AlmostRobot.extend({id: Uid});

export default {
  AlmostRobot,
  Robot
};
```

**Comment by ivan-kleshnin** [comment]
> At design time I use the extend function

Fantastic! This exactly covers my case.
I somehow missed this function.
