### ISSUE TITLE
Determining supertypes/inheritence?

### ISSUE THREAD

**Issue by R3D4C73D** [gcanti/tcomb#197]
Is there a way to tell if type A is a subtype of type B programmatically?  For example...

```es6
const Integer = t.refinement(t.Number, (n) => n % 1 === 0, 'Integer');
Integer.isSubtypeOf(t.Number);  // true
Integer.isSubtypeOf(t.String);  // false
```

My use-case is that I'm using tcomb to determine whether it's valid to assign a value of type A to a variable of type B.  Obviously, if I had an explicit value in mind, I could just do `t.Number.is(x)`, but in my case, I don't have an explicit value.  I have two variables, one of type A and one of type B.  I'm going to be assigning the hypothetical value of A to B, but I don't know what that value will be at runtime.

If I just did regular comparison (`typeA === typeB`) that would work for exact matches, but what about when type A is a subtype of type B?  An exact match won't catch it, but they're still technically compatible going from a more specific type to a more general type.

```es6
var a;  // type Integer
var b;  // type t.Number

// Some stuff happens that assigns a value to a

// If I check for typeof a === typeof b, this will seem to be invalid.
// But all Integers are valid Numbers.
b = a;
```

Any ideas on how to implement this?  Perhaps walking through `meta.type` and `meta.types`?  Should this be incorporated into the library or should this just be part of my project's code?

Thanks for all the work on tcomb, @gcanti.  It's been a very valuable tool.

**Comment by gcanti** [comment]
Hi @jv-PintoBobcat,

I think that the problem ends up in establishing the formal meaning of "A is a subtype of B" i.e. what's the (mathematical) relation between A and B. In the case of `tcomb`, which is grounded on set theory, types represent sets (see also The Curry-Howard Correspondence and the work of Martin-Löf) so a *natural* formalization would be **"A is a subtype of B is and only if the set represented by A is a subset of the set represented by B"**.

The `subset` relation is a pretty good candidate since it's an [order](https://en.wikipedia.org/wiki/Order_theory), i.e. the following properties hold:

- `a ≤ a` (reflexivity)
- if `a ≤ b` and `b ≤ a` then `a = b` (antisymmetry)
- if `a ≤ b` and `b ≤ c` then `a ≤ c` (transitivity).

Now if we consider refinements it seems reasonable to conjecture (must be proved) that at least reflexivity and transitivity hold (which ensure that the refinement relation is a [preorder](https://en.wikipedia.org/wiki/Preorder)). But what about antisymmetry? If **we exclude pathological cases** (recursive types):

```js
const A = t.declare('A')
const B = t.declare('B')
A.define(t.refinement(B, () => true))
B.define(t.refinement(A, () => true))
console.log(A.meta.type === B) // true
console.log(B.meta.type === A) // true

// so A <= B, B <= A but A is NOT equal to B
```

then also **antisymmetry holds**.

Coming to the implementation:

> Perhaps walking through `meta.type`

Yup (for refinements). 

In the case of other type kinds (structs, tuples, lists, etc...), if they are of interest, we should come up with rules that reflect the formal definition above.

> Should this be incorporated into the library or should this just be part of my project's code?

If we come up with something solid, it could be an optional module (something like `tcomb/lib/isSubsetOf`).

**Comment by jv-PintoBobcat** [comment]
Thanks for the prompt response. You've given me a lot to think about.

As this feature is necessary for a project I'm working on, I'm going to take a stab at this (backed by many tests, of course). Something is better than nothing. I'll be sure to file a PR if I come up with anything useful.

**Comment by gcanti** [comment]
> Something is better than nothing. I'll be sure to file a PR if I come up with anything useful

Great, thanks @jv-PintoBobcat. Let me know if I can help in any way.

**Comment by R3D4C73D** [comment]
https://github.com/gcanti/tcomb/pull/207

**Comment by gcanti** [comment]
Hi @R3D4C73D,

Thanks for the PR. Sorry for the delay, alas these days I'm very busy. I'll take a look as soon as possible. Also I'm working on a spec based on my first comment and your implementation.

**Comment by gcanti** [comment]
This is a first draft. Some conditions are subtle so anyone willing to double check is warmly welcomed.

### Goal

> to determine whether it's valid to assign a value of type A to a variable of type B

**Signature**

```js
// reads: is A a subset of B?

isSubsetOf(A: Type, B: Type): Boolean
```

### Spec

If `A` is a subset of `B` we write `A <= B` (since "is a subset of" is an order relation).

**Fast results**

- (1) if `B === t.Any` then `A <= B` for all `A`
- (2) if `B === A` then `A <= B` for all `A`

**Reductions**

Here the goal is to reduce the complexity of the computation when `B` is a union or an intersection (maybes are just special kinds of unions):

- (3) if `B = maybe(C)` and `A` is not a maybe then `A <= B` if and only if `A === t.Nil` or `A <= C`
- (4) if `B` is a union then `A <= B` if exists `B' in B.meta.types` such that `A <= B'`
- (5) if `B` is an intersection then `A <= B` if `A <= B'` for all `B' in B.meta.types`

> **Important**. From now on we'll assume that none of (1), (2), (3), (4), (5) holds.

**Maybes**

Let `A` be a maybe then `A <= B` if `B` is a maybe and `A.meta.type <= B.meta.type`

**Unions**

Let `A` be an union then `A <= B` if `A' <= B` for all `A' in A.meta.types`.

**Intersections**

Let `A` be an intersection then `A <= B` if exists `A' in A.meta.types` such that `A' <= B`:

**Irreducibles**

Let `A` be irreducible then `A <= B` if `B` is irreducible and `A.is === B.is`.

**Enums**

Let `A` be an enum then `A <= B` if and only if `B.is(a) === true` for all `a in keys(A.meta.map)`

**Refinements**

Let `A` be a refinement then `A <= B` if `decompose(A) <= decompose(B)` (see https://github.com/gcanti/tcomb/issues/179#issue-131567752 and `lib/extend.js` for the definition of `decompose`) where:

```
{ predicates1, unrefinedType1 } <= { predicates2, unrefinedType2 }
```

if and only if `predicates2 <= predicates1` and `unrefinedType1 <= unrefinedType2` where:

```
// lists of predicates
[a1, ..., an] <= [b1, ..., bm]
```

if and only if `n <= m` and for all `ai in [a1, ..., an]` then `ai in [b1, ..., bm]`.

**Lists**

Let `A` be a list then `A <= B` if one of the following holds:

- `B === t.Array`
- `B` is a list and `A.meta.type <= B.meta.type`

**Dictionaries**

Let `A` be a list then `A <= B` if one of the following holds:

- `B === t.Object`
- `B` is a dictionary and `[A.meta.domain, A.meta.codomain] <= [B.meta.domain, B.meta.codomain]` where:

```
// lists of types
[a1, ..., an] <= [b1, ..., bm]
```

if and only if `n === getOptionalArgumentsIndex(m) + 1` and for all `i = 1 ... n` then `ai <= bi` (see `lib/func.js` and https://github.com/gcanti/tcomb/issues/198#issuecomment-217097264 for the definition of `getOptionalArgumentsIndex`).

**Tuples**

Let `A` be a tuple then `A <= B` if one of the following holds:

- `B === t.Array`
- `B` is a tuple and `A.meta.types <= B.meta.types`

**Structs**

Let `A` be a struct then `A <= B` if `B === t.Object`.

**Functions**

Let `A` be a function then then `A <= B` if one of the following holds:

- `B === t.Function`
- `B` is a function and `[A.meta.domain, A.meta.codomain] <= [B.meta.domain, B.meta.codomain]`

**Interfaces**

Let `A` be an interface then:

First case: if `A.meta.strict === false` then `A <= B` if one of the following holds:

- `B === t.Object`
- `B` is an interface, `B.meta.strict === false` and `A.meta.props <= B.meta.props` where:

```
PropsA = { a1: A1, ..., an: An } <= { b1: B1, ..., bm: Am } = PropsB
```

if and only if `keys(PropsA) <= keys(PropsB)` and `Ak <= Bk` for all `k` in `keys(PropsA)`.

Second case: if `A.meta.strict = true` then `A <= B`  if one of the following holds:

- `B === t.Object`
- if `B` is an interface, `B.meta.strict === true`, `keys(PropsA).length === keys(PropsB).length` and `A.meta.props <= B.meta.props`.

**Comment by R3D4C73D** [comment]
Most of this looks good to me, although it mostly matches my implementation. ;-)

One thing of note, in my implementation I completely punted on unions mostly because I don't quite understand them.  So, in my PR, unions only return true if they are literally equal.

**Comment by R3D4C73D** [comment]
Also, I was unaware of the bit about optional arguments (https://github.com/gcanti/tcomb/issues/198#issuecomment-217097264) which I think may be in the wrong section.  It's currently listed in the Dictionary section, but I believe that only applies to Functions.

**Comment by gcanti** [comment]
> although it mostly matches my implementation

Indeed! You did a great job, it helped me a lot while writing that spec.
There are some differences though, I'll try to list'em all in the week-end.

> It's currently listed in the Dictionary section, but I believe that only applies to Functions.

But a dictionary **is** a function. It has a `domain` and a `codomain`. Actually a dictionary is a function in disguise:

*Math point of view*

Let `f` a function `f: String -> String` such that:

```
f('IT') = 'Italy'
f('US') = 'United States'
```

function application: `f(x)`

*JavaScript point of view*

```js
// String -> String
const f = {
  IT: 'Italy',
  US: 'United States' 
}
```

"dictionary application": `f[x]` (parens replaced by brackets)

It's the reason why dictionaries are also named "maps".

**Comment by R3D4C73D** [comment]
Definitely let me know in which behaviors my implementation falls short.  I'm right in the middle of a really stressful move right now, so I don't know if I'll be able to address the shortcomings immediately.  Feel free to jump in and change the code.  Some failing tests would be super helpful for me to code against.

**Comment by gcanti** [comment]
> I'll try to list'em all in the week-end

@R3D4C73D even better: here's a test suite with your tests plus mine https://github.com/gcanti/tcomb/blob/197/test/isSubsetOf.js
and here's an implementation based on the spec above https://github.com/gcanti/tcomb/blob/197/lib/isSubsetOf.js

One doubt though: in your implementation you handle instrumented functions but I don't understand why, they are values not types. I can't apply `isSubsetOf(value, type)` to a value and a type.

**Comment by R3D4C73D** [comment]
I agree about instrumented functions.  I felt weird adding that code in there.  However, I guess that's a separate feature request.  I'm unaware of any way to detect instrumented functions from regular functions without knowing implementation details of the library.  Also, once you've confirmed you have an instrumented function, I'm unaware of a way to get the type from the function.

One big difference I've noticed between your implementation and mine is that you're doing a bunch of comparison between kind and string literals.  I preferred going for separate functions to detect if something is of a type.  The reasoning for that was so there was one canonical place in the code that does that detection.  That way, if later down the line you should decide to change what that string literal is, there's only one place in the code where you have to change that comparison instead of the `isSubsetOf` code, and the `fromJSON` code, and wherever else.

**Comment by gcanti** [comment]
> However, I guess that's a separate feature request. I'm unaware of any way to detect instrumented functions from regular functions without knowing implementation details of the library

Could you expand on your use case? Given an element `x`, you can't retrieve its type (set) `X` because there are several candidates: the number `1` belongs to the set `t.Number` but also to the set `t.Integer`, so in general it doesn't exist a relation `value -> Type`. Instrumented functions could be an exception though, so maybe you have a use case for which this does make sense.

> you're doing a bunch of comparison between kind and string literals

Ah yes, yours is definitely a better style.

> if later down the line you should decide to change what that string literal is

however this is hardly going to happen: the `meta` objects are considered APIs, changing one of those strings would be a brutal breaking change (it's the reason why refinements still have the old kind `"subtype"`) and API stability is my first priority (for all my libraries, but in particular for `tcomb`)

**Comment by R3D4C73D** [comment]
I feel like instrumented functions are a special case. Whereas most values
aren't intrinsically tied to a tcomb type, instrumented functions are. So,
just as it makes sense to tie a type to its implementation, it makes as
much sense to be able to untangle the type from the implementation as well.

**Comment by gcanti** [comment]
> But I think this is a discussion for another ticket

Ok, I'd love to talk about it further.

For what concerns recursive types, the current implementation would raise a stack overflow. 

A possible solution could be to store the already processed types, here's a POC: https://github.com/gcanti/tcomb/commit/8b4f8b64950eee0df0744682c260fda4a56f5345

**Comment by R3D4C73D** [comment]
I didn't even consider recursive types. Nice catch. I'm cool with this.

**Comment by R3D4C73D** [comment]
Is there an ETA on 3.2.0?  Just curious as I need this feature for a project I'm working on.

**Comment by R3D4C73D** [comment]
Sure!  I'm creating a lisp-based visual programming language.  The code editor is a web application.  I'm using tcomb to enforce types so users are incapable of creating type errors.  Or, at least, that's the goal.
