### ISSUE TITLE
Optional `func` params 

### ISSUE THREAD

**Issue by ivan-kleshnin** [gcanti/tcomb#198]
1) `.func().of()` pair seems to not support optional params.

2) We have `.maybe()` so I'm trying this.

```js
let T = require("tcomb")

let MaybeString = T.maybe(T.String, "MaybeString")

console.log(MaybeString(undefined)) // works!
console.log(MaybeString(null)) // works!
```

But then:

```js
let Type = T.irreducible("Type", T.isType)

// Number, Type, MaybeString -> Type
let vect = T
  .func([T.Number, Type, MaybeString], Type)
  .of((n, a, name) => {
    let Vect = T.refinement(T.list(a), (x) => {
      return x.length == n
    }, name || `Vect(${n})`)
    Vect.meta.size = n
    return Vect
  })

console.log(vect(2, T.Number)([1, 2])) // throws!
console.log(vect(2, T.Number, null)([1, 2])) // works!
console.log(vect(2, T.Number, undefined)([1, 2])) // works!
```

Looks like a bug to me.

**Comment by gcanti** [comment]
Actually it's a (admittedly arbitrary) design decision: `tcomb` uses a tuple in order to type-check the arguments, thus functions handled by `func` combinator have **fixed arity**. 
Historically this is due to the fact that in v1.0.0 `func`ed functions were curried by default. This was confusing for some users so starting from v2.0.0 `func`ed functions are no more curried by default (you must explicity pass `of()` a second argument `true`).
I guess that in case of non-curried functions we can relax that constraint, but first we must formalize the concept of *optional arguments*. 

I'll try my hand:

**Definition**. Let `f: A -> B` be a JavaScript function, where `A = [T_1, T_2, ...]` is an infinite tuple of types, then we say that `f` has *optional arguments* if exists `n, m in Natural` such that:

- `m > n`
- `forall i in Natural` such that `n < i <= m` then `T_i` is a maybe
- `forall i in Natural` such that `i > m` then `T_i = t.Any`


*Diagram*

```
+--required args--+    +--optional args-+
|                 |    |                |
[T_1, T_2, ... , T_n, T_{n + 1}, ... , T_m, t.Any, t.Any, t.Any, t.Any, ...]
```

**Checks that `func` should implement**

Let `len = arguments.length`, then:

- `len` must be `>= n`
- the sub-tuple `[T_1, T_2, ... , T_{len}]` must be type-checked

What do you think?

**Comment by ivan-kleshnin** [comment]
I think you've pretty much nailed it.

> the sub-tuple [T_1, T_2, ... , T_{len}] must be type-checked

What do you mean by **sub**-tuple? If `len = arguments.length` then `[T_1, T_2, ... , T_{len}]` will cover all passed arguments or no?

**Comment by gcanti** [comment]
Oh I simply mean that `len` must be `>= n` but can also be `<= m`, so `[T_1, T_2, ... , T_{len}]` in general is a "sub-tuple" of the whole domain `[T_1, T_2, ... , T_m]`

**Comment by ivan-kleshnin** [comment]
Then all seems fine to me 👍

**Comment by gcanti** [comment]
PR here https://github.com/gcanti/tcomb/pull/201 if you want to review and/or to test

**Comment by gcanti** [comment]
Closing via https://github.com/gcanti/tcomb/commit/a1cf5f39a7b9408a4133b474f87ce9e56ff4c516

**Comment by ivan-kleshnin** [comment]
Thanks. I've just tested it – looks fine.
