### ISSUE TITLE
Detect if a hash contains properties not specified on a struct type

### ISSUE THREAD

**Issue by gavacho** [gcanti/tcomb#86]
Given a type like `var Point = struct({ x: Num, y: Num })` and a hash like `var hash = {x: 1, y: 2, z: 3}`, the result of `Point(hash)` is what you might expect `{x: 1, y: 2}`.

In the case where `hash` is being passed into my function, I would like to inform the caller (e.g. by throwing) if they provide an unexpected property like `z`.  Is this possible already?

**Comment by beckyconning** [comment]
This isn't part of tcomb currently. It would take a more expensive kind of check to make these sorts of assertions. You can see a minimal implementation of the `struct` combinator here http://gcanti.github.io/2014/09/29/javascript-types-and-sets.html. 

```javascript
// `struct` combinator
function struct(props) {
  // `Struct` constructor
  return function Struct(obj) {
    // makes Struct idempotent
    if ( obj instanceof Struct ) return obj;
    // makes new optional
    if ( !(this instanceof Struct) ) return new Struct(obj);
    // check input structure
    assert(isObject(obj));
    var ret = {};
    for (var name in props) {
      if (props.hasOwnProperty(name)) {
        var type = props[name];
        ret[name] = type(obj[name]); // check prop type and hydrate nested structures
      }
    }
    return Object.freeze(ret);
  };
}
```

Here we loop through all the `Struct` type's properties (ensuring we don't use inherited properties such as those provided by javascript to every object)

```javascript
    for (var name in props) {
      if (props.hasOwnProperty(name)) {
```

Then we get the property value from the object provided to Struct constructor, pass it to relevant type and assign it to a property of an object that we eventually return.

```javascript
var type = props[name];
        ret[name] = type(obj[name]); // check prop type and hydrate nested structures
```

So you can see that we use the list of keys from the type to retrieve the values from the provided object rather than the other way around.

This means that asserting the condition you are suggesting would take an extra check which wouldn't come too cheaply. The current way is just as "type safe" as it constrains provided objects to match the type. It doesn't warn you if you pass extraneous properties to the Struct constructor though. 

I'd be interested to know what situations you're envisioning using this in though : ). Just because its an extra check doesn't mean it can't be done if its useful.

**Comment by beckyconning** [comment]
The current implementation treats the type like a shopping list and the provided object as a store. Tcomb doesn't complain if the store has things we don't need. It only complains if the store sells us something that was mislabeled or not what it seemed.

**Comment by gavacho** [comment]
Yeah, I can definitely understand why the default isn't to throw on unexpected properties.  Since there's nothing built-in I'll implement my own check via `meta` (e.g. `_.difference(_.keys(hash), _.keys(Point.meta.props))`).
