### ISSUE TITLE
Tcomb vs Flowtype 

### ISSUE THREAD

**Issue by volkanunsal** [gcanti/tcomb#98]
I just stumbled on this repo today. It's awesome to see a project that is introducing math concepts to Javascript. My naive question seeing this for the first time, How is it different from a type system like Flow? The struct types, union types, etc., are all being built into Flow compiler, and you can get the benefit of them by syntactic constructs. How can we differentiate the use case of tcomb from the usecase of Flow? Would you still need to use tcomb if you are already using Flow?

**Comment by gcanti** [comment]
Hi!

> Would you still need to use tcomb if you are already using Flow?

In theory nope, in practice yes. The main advantages of tcomb are:

- you can extend the type system with your custom types
- you can define subtypes (e.g. the type Email which is a subtype of string)
- it's just JavaScript, hence it plays well with the other tools of the JavaScript ecosystem

In my experience using Flowtype, babel (ES6, ES7, ES8??) and eslint together can quickly become a nightmare.
Using tcomb instead of Flowtype as a type checker is seamless.
Obviously you also lose something (method names typos, ecc...), but it's a price I definitely want to pay.
I think that runtime type checking + a good test suite is enough to achieve a high level of type safety.

Having said that, in the future I really hope tcomb will become useless, but these days and for my usecase, it's a invaluable development tool.

**Comment by volkanunsal** [comment]
Awesome. The other nice thing about tcomb is that it gives you a type system you can use in the runtime. This couldn't be done with Flowtype unless the type system is added to the language runtime.

**Comment by chcokr** [comment]
@gcanti Just curious, why do you anticipate that tcomb will hopefully become useless?

**Comment by gcanti** [comment]
Well, it's just... a dream: frontend development with a strong static type system. 

(speaking of static type checkers / transpilers, I'm quite interested in PureScript)

However there are 2 points for which tcomb will probably be still relevant in the future:

- user defined types and `refinements` are VERY powerful (type checkers will validate `strings` but I want to type check `Emails`, `URLs`, lists with at least 2 items, etc...)
- runtime type introspection: this is HUGE for me. It allows automatic JSON serialization / deserialization and libraries like `tcomb-validation` (only 230 LOC!) or `tcomb-form`. There are invaluable informations stored in your types, they describe the domain of your application. Throwing away that info with type erasure it's a shame

**Comment by chcokr** [comment]
Right! And I don't think any static type system will ever get that far.

And yeah, things like `tcomb-form` are amazing.

> automatic JSON serialization

Can you point me to an example of this?

**Comment by chcokr** [comment]
Oops, never mind, I found https://gcanti.github.io/2014/09/12/json-deserialization-into-an-object-model.html

**Comment by itajaja** [comment]
since this is the number 1 result on google for "tcomb flow" and related searchig, it might be relevent to link to https://github.com/gcanti/babel-plugin-tcomb/issues/48
